---
name: Build Firmware

on:
  push:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - "ekh-bcm2710"
          - "ekh-bcm2711"
          - "venice"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install deps
        run: |
          sudo apt update && sudo apt install build-essential clang flex g++ gawk gcc-multilib g++-multilib git gettext \
            libncurses5-dev libssl-dev python3-setuptools rsync unzip zlib1g-dev swig file wget libnl-3-dev \
            libnl-genl-3-dev libgps-dev libcap-dev pkg-config libopus-dev \
            libopusfile-dev portaudio19-dev net-tools libpcre3-dev libpcre3
        
      - name: Run Setup Script
        run: |
          ./scripts/openmanet_setup.sh -i -b  ${{ matrix.target }}
     
      - name: Download Deps
        run: |
          make download

      - name: Build
        run: |
          make -j4 V=sc

      - name: Debug
        run: |
          pwd
          ls -al
          ls bin/target/
